### PR TITLE
fix/icon alignment

### PR DESCRIPTION
**Pull request by kabouzeid**
## The problems

1. icons were aligned to far at the top
2. octicons weren't aligned correctly because they had different sizes (not all of them were 16x16)

## What I've done

- re-copy octicons from upstream (https://github.com/primer/octicons)
- use oslllo-svg-fixer to patch the SVG fill rules (https://github.com/oslllo/svg-fixer) instead of manually doing it with the figma plugin
- set descent to 40
- fix typo vim-nomal-mode-16 -> vim-normal-mode-16

## Result
It looks *much* better now. Icons are finally aligned in neovim 😍

### CODE REVIEW

**Comment by yamatsum** [comment]
Thanks for the great suggestions!
I verified it step by step and adopted oslllo-svg-fixer because it worked well.
At the same time, it also supports the latest version of octicons.

But I have one question, "descent" doesn't seem to work well
Is there any concrete example?

**Comment by kabouzeid** [comment]
Look at the circle with the cross in the bottom right for comparison.

**descent=40**
descent_40
**no descent**
no_descent

You can try it yourself with eg `:lua print(require'nvim-nonicons'.get('info') .. ' 2')` in neovim to see that the icons are not aligned with the text

**Comment by kabouzeid** [comment]
macOS 11.2.3, kitty 0.20.3

[nonicon_fonts.zip](https://github.com/yamatsum/nonicons/files/6471776/nonicon_fonts.zip)

**Comment by yamatsum** [comment]
Is it possible to display correctly with the font generated using descent using the current master?
As far as I try, it's crumbled before and after use

**Comment by kabouzeid** [comment]
No, you need descent *and* replace the octicons with the original 16x16 versions.

This PR contains an updated `package.json`, `.fantasticon.rc.js` and the original octicons.

**Comment by kabouzeid** [comment]
You’ve seem to have fixed it. Thanks :)

**Pull request closed without merging**
